name: Prepare autofilled template for library metadata
on:
  issue_comment:
    types: [created]

jobs:
  Autofill:
    # Only run if comment is on a PR with the main repo, and if it contains the magic keywords
    if: >
      contains(github.event.comment.html_url, '/pull/') &&
      startsWith(github.event.comment.body, '@spaam-bot please autofill') &&
      github.repository == 'SPAAM-community/AncientMetagenomeDir'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      PR_NUMBER: ${{ github.event.number }}    
    steps:
      # indication that the process has started
      - name: React on comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes
          token: ${{ secrets.GITHUB_TOKEN }}

      # install AMDirT
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install amdirt==1.5.0
          pip install jsonschema==4.17.0

      # Post results
      - name: Get PR number
        id: pr_number
        run: echo "pr_number=$(cat linting-logs/PR_number.txt)" >> $GITHUB_OUTPUT

      - name: Post PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ PR_NUMBER }}
          message: "Success"